version: '3.6'

services:
  api:
    volumes:
      - notused:/srv/app/node_modules
      - notused-client:/srv/app/client-auth/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:10.14-alpine
    volumes:
      - psql-data:/var/lib/postgresql/data/

volumes:
  psql-data:
  notused:
  notused-client:
