version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.2
        environment:
        - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/circle_test
        - ALLOW_UNSECURE=1
        - DOMAIN=localhost:3001
        - PORT=3001
      - image: postgres:10.4-alpine
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=circle_test
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.1.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: puppeteer-dependencies
          command: |
            sudo su - << 'EOF'
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

              apt-get update
              apt-get install $( \
                dpkg -I google-chrome-stable_current_amd64.deb | \
                awk '/^ Depends: / { gsub(/Depends:|,|\([^\)]*\)/, ""); print }' \
              )
            EOF
      - run:
          name: test
          command: npm run migrate up && npm test
