version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
        environment:
        - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/circle_test
      - image: postgres:9.6
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=circle_test
    steps:
      - checkout
#      - run:
#        name: update-npm
#        command: 'sudo npm install -g npm@5.5.1'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
