version: 2

node-image: &node-image
  image: circleci/node:10.8

set-npm-global: &set-npm-global
  run:
    name: set-npm-global
    command: |
      mkdir -p ~/.npm-global
      npm config set prefix '~/.npm-global'
      echo 'export NPM_CONFIG_PREFIX=~/.npm-global' >> $BASH_ENV
      echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      source $BASH_ENV
save: &save
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .
      - ".git"
      - "~/.npm-global"

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

jobs:
  install:
    docker:
      - <<: *node-image
    steps:
      - checkout
      - <<: *set-npm-global
      - run: npm install -g npm@6.3.0
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: greenkeeper
          command: |
            npm install -g greenkeeper-lockfile
            greenkeeper-lockfile-update
            greenkeeper-lockfile-upload
      - run: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - <<: *save
  lint:
    docker:
      - <<: *node-image
    steps:
      - <<: *restore
      - run: npm run lint
  test:
    docker:
      - <<: *node-image
        environment:
          - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/circle_test
          - ALLOW_UNSECURE=1
          - DOMAIN=localhost:3001
          - PORT=3001
      - image: postgres:10.5-alpine
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=circle_test
    steps:
      - <<: *restore
      - run:
          name: puppeteer-dependencies
          command: |
            sudo su - << 'EOF'
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

              apt-get update
              apt-get install $( \
                dpkg -I google-chrome-stable_current_amd64.deb | \
                awk '/^ Depends: / { gsub(/Depends:|,|\([^\)]*\)/, ""); print }' \
              )
            EOF
      - run:
          name: test
          command: npm run migrate up && npm test


workflows:
  version: 2
  main_workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
