version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0
        environment:
        - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/circle_test
        - ALLOW_UNSECURE=1
        - DOMAIN=localhost:3001
        - PORT=3001
      - image: postgres:10.3
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=circle_test
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.0.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: puppeteer-dependencies
          command: sudo apt-get update && sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libcups2 libdbus-1-3 libgconf-2-4 libgtk-3-0 libnspr4 libxcomposite1 libxcursor1 libxi6 libxrandr2 libxss1 libxtst6 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
      - run:
          name: test
          command: npm test
